# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BtcRate',
        ),
        migrations.RemoveField(
            model_name='btcprice',
            name='date',
        ),
        migrations.RemoveField(
            model_name='btcprice',
            name='volume_btc',
        ),
        migrations.RemoveField(
            model_name='btcprice',
            name='volume_currency',
        ),
        migrations.RemoveField(
            model_name='btcprice',
            name='weighted_price',
        ),
        migrations.AddField(
            model_name='btcprice',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
